language: android

android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew
    - npm install awsdevicefarmcli

script:
    - ./gradlew build
    - ls
    - mv /home/travis/build/dcampogiani/Panaro/app/build/outputs/apk/app-debug.apk ./app.apk
    - ls
    - node ./node_modules/awsdevicefarmcli/downloadTests.js --gitHubAccessToken ${gitHubAccessToken} --repoUser ${testRepoUser} --repoName ${testRepoName} --output ${testZipOutput}
    - ls
    - node ./node_modules/awsdevicefarmcli/scheduleRun.js --AWSAccessKeyId ${AWSAccessKeyId} --AWSSecretAccessKey ${AWSSecretAccessKey} --AWSRegion ${AWSRegion} --AppApk app.apk --TestsZip ${testZipOutput}