language: android

android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
    - chmod +x gradlew
    - chmod +x scripts/*.sh
    - npm install github-changes
    - npm install awsdevicefarmcli
    - npm install slack-cli

script:
    - ./gradlew build
    - scripts/generate-changelog.sh

after_success:
    - scripts/costanzo-ci.sh success
    - scripts/upload-to-fabric.sh
    - mv /home/travis/build/dcampogiani/Panaro/app/build/outputs/apk/app-release.apk ./app.apk
    - node ./node_modules/awsdevicefarmcli/downloadTests.js --gitHubAccessToken ${gitHubAccessToken} --repoUser ${testRepoUser} --repoName ${testRepoName} --output ${testZipOutput}
    - node ./node_modules/awsdevicefarmcli/scheduleRun.js --AWSAccessKeyId ${AWSAccessKeyId} --AWSSecretAccessKey ${AWSSecretAccessKey} --AWSRegion ${AWSRegion} --AppPath app.apk --TestsZipPath ${testZipOutput}

after_failure:
    - scripts/costanzo-ci.sh failure
